client/presentation/src/main/java/com/everyone/movemove_android/ui/main/MainScreen.kt
resolved: #18 
-네비게이션 바 border 추가
- 네비게이션 바 ripple 제거
- 네비게이션 바 색상 수정
- 코딩 컨벤션 적용
=> 바텀 네비게이션 스타일 수정

client/gradle/libs.versions.toml, client/presentation/build.gradle.kts, client/presentation/src/main/AndroidManifest.xml, client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Type.kt
resolved: #8
- 숏 폼 UI
- 비디오 스트리밍
- 비디오 스트리밍 상하 스크롤
- 데이터값은 임시로 정의하여 구현했습니다.
- data class 구현 시 수정하도록 하겠습니다.
- 숏 폼 상하로 스크롤 시 비디오가 살짝 느리게 실행될 경우, 하단 컨텐츠의 색상과 비디오 백그라운드 색상이 분리되어 보이는 현상이 발생합니다.
- 비디오 스트리밍에 대해 학습하여 개선해 나가겠습니다.
- 가로가 긴 비디오와 세로가 긴 비디오를 각각 어떤 식으로 대응할지 고민하고 있습니다.
=> 숏 폼 비디오 스트리밍

server/src/app.controller.ts, server/src/ncpAPI/common.ts, server/src/ncpAPI/getObject.ts, server/src/ncpAPI/putObject.ts
related To: #26
- NCP Object Storage의 Get Object API 작성
- Put Object API와 큰 차이가 없으나, 기존 Authorization header의 잘못된 부분을 같이 수정하였습니다.
=> NCP 다운로드 API 작성

client/gradle/libs.versions.toml, client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
resolved: #27 
- HLS 비디오 스트리밍
- 더미 데이터 수정
=> HLS 비디오 스트리밍

server/src/app.controller.ts, server/src/ncpAPI/deleteObject.ts, server/src/ncpAPI/requestEncoding.ts
resolved: #26 
- NCP Object Storage의 Delete Object API 작성
- Get Object API와 거의 동일합니다
- requestEncoding.ts 변수명 수정
=> NCP 삭제 API 작성

client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
resolved: #28 
- 비디오 스트리밍 리소스 최적화
- 비디오 스트리밍 스크롤 시 동시성 이슈
- 세 개의 ExoPlayer 인스턴스를 미리 생성하여 재활용하여 리소스 효율성을 개선했습니다.
- VideoPlayer에서 스크롤 중인지 여부를 확인하여 플레이어 동작을 동적으로 조절하여 성능을 향상시켰습니다.
=> 비디오 스트리밍 최적화

client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt, client/presentation/src/main/res/values/strings.xml
resolved: #29
- 비디오 스트리밍 점수 등록 UI 구현
=> 비디오 스트리밍 점수 등록

client/presentation/src/main/java/com/everyone/movemove_android/base/BaseViewModel.kt, client/presentation/src/main/java/com/everyone/movemove_android/di/CoroutineDispatcherModule.kt, client/presentation/src/main/java/com/everyone/movemove_android/di/CoroutineDispatcherQualifiers.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/CommonComposables.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/Dialogs.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/main/MainActivity.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/main/uploading_video/UploadingVideoContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/main/uploading_video/UploadingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/main/uploading_video/UploadingVideoViewModel.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/main/uploading_video/VideoTrimmer.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/util/ComposableUtil.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/util/Util.kt, client/presentation/src/main/res/drawable/ic_pause.xml, client/presentation/src/main/res/drawable/ic_play.xml, client/presentation/src/main/res/values/strings.xml
resolved: #23
- 영상 불러오기 및 재생 기능 구현
- 컷 편집 UI 구현
- 영상 컷 편집 기능 구현
=> 영상 편집 기능 구현

client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/category/CategoryScreen.kt
resolved: #51
- 카테고리 목록 안나오는 이슈 해결
=> 카테고리 목록 안나오는 이슈

client/gradle/libs.versions.toml, client/presentation/src/main/java/com/everyone/movemove_android/ui/main/MainScreen.kt
Related To: #22, #46
resolved: [이슈]
- `androidx.navigation:navigation-compose` 의존성 추가
- 애니메이션 제거를 일괄 적용하기 위해 `composable` 대신 `navScreen` `Composable` 구현
https://github.com/boostcampwm2023/and03_movemove/assets/82919343/e869c889-7017-4958-b8c6-0adaaa759670
=> 스크린 변경 애니메이션 삭제

client/domain/src/main/java/com/everyone/domain/model/Category.kt, client/gradle/libs.versions.toml, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoViewModel.kt, client/presentation/src/main/res/values/strings.xml
resolved: #48 
- 영상 업로드 화면 바텀 시트 추가
- 이벤트 연결
=> 영상 업로드 화면 바텀 시트 추가

server/src/auth/auth.service.ts, server/src/enum/exception.enum.ts, server/src/exceptions/base.exception.ts, server/src/exceptions/conflict.exception.ts, server/src/exceptions/invalid-refresh-token.exception.ts, server/src/exceptions/invalid-token.exception.ts, server/src/exceptions/login-fail.exception.ts, server/src/exceptions/oauth-failed.exception.ts, server/src/exceptions/token-expired.exception.ts, server/src/main.ts, server/src/video/video.controller.ts, server/src/video/video.module.ts
resolved: #69 
- 비디오 업로드 시 인증 추가
=> 인증 및 비디오 업로드 통합

server/src/app.controller.ts, server/src/auth/auth.controller.ts, server/src/decorators/api-succes-response.ts, server/src/decorators/request-user.ts, server/src/enum/exception.enum.ts, server/src/exceptions/base.exception.ts, server/src/exceptions/not-your-video.exception.ts, server/src/exceptions/video-not-found.exception.ts, server/src/http-Exception.filter.ts, server/src/user/dto/profile-response.dto.ts, server/src/user/dto/user.dto.ts, server/src/video/schemas/video.schema.ts, server/src/video/video.controller.ts, server/src/video/video.service.ts
resolved: #72 
- 기능
- DB에서 비디오 정보 삭제
- Object Storage에서 원본 비디오, 인코딩된 비디오, 썸네일 삭제
- 예외처리
- 존재하지 않는 비디오 
- 업로더가 아닌 경우 
- Swagger Api 명세 데코레이터 수정
- request.user 타입 Param 데코레이터 작성
=> 업로드한 비디오 삭제

server/.gitignore, server/src/auth/auth.module.ts, server/src/auth/auth.service.ts, server/src/video/video.service.ts
resolved: #78 
- 버그 수정
- Jwt 시크릿 키 입력 오류 수정
- 프로필 이미지 응답 오류 수정
- 기능 
- Manifest URL 응답 추가
- 현재 버전으로 수동 배포하였습니다
=> 버그 수정 및 Manifest 응답

client/build.gradle.kts, client/data/build.gradle.kts, client/data/src/main/java/com/everyone/data/base/BaseResponse.kt, client/data/src/main/java/com/everyone/data/remote/NetworkHandler.kt, client/data/src/main/java/com/everyone/data/remote/UrlParams.kt, client/data/src/main/java/com/everyone/data/remote/UrlParamsBuilder.kt, client/domain/build.gradle.kts, client/gradle/libs.versions.toml, client/presentation/build.gradle.kts
resolved: #68
- `Ktor` 적용
- `Generics` 기반의 네트워크 핸들러 구현
- 사용법에 관해서는 월요일 팀 스크럼 이후에 전파하겠습니다.
=> 네트워크 통신 셋업

client/data/src/main/java/com/everyone/data/remote/UrlParams.kt, client/data/src/main/java/com/everyone/data/remote/UrlParamsBuilder.kt
resolved: #90 
- `path` 를 `vararg` 로 받고 있는데, 이를 `List<String>` 으로 감싸지 않도록 수정
=> UrlParamsBuilder 수정

server/src/action/schemas/action.schema.ts, server/src/app.service.ts, server/src/ncpAPI/getBucketImage.ts, server/src/transform.interceptor.ts, server/src/user/dto/uploaded-video-response.dto.ts, server/src/user/dto/uploader-response.dto.ts, server/src/user/schemas/user.schema.ts, server/src/user/user.controller.ts, server/src/user/user.service.ts, server/src/video/dto/random-video-response.dto.ts, server/src/video/dto/video-info.dto.ts, server/src/video/dto/video-response.dto.ts, server/src/video/dto/video-summary-response.dto.ts, server/src/video/schemas/video.schema.ts, server/src/video/video.controller.ts, server/src/video/video.service.ts
resolved: #104 
- feat
- DTO 추가
- Swagger 명세 수정
- refactor
- 광고 조회 코드 수정
- getBucketImage 함수 파일화
- Video와 VideoInfo 명칭 구분
- 응답 딜레이 로그 추가
- DB 스키마 내 versionkey 삭제
=> Swagger 명세 구체화

server/nest-cli.json, server/src/action/action.module.ts, server/src/action/action.service.ts, server/src/action/schemas/action.schema.ts, server/src/app.controller.ts, server/src/auth/auth.controller.ts, server/src/exceptions/enum/exception.enum.ts, server/src/exceptions/never-view-video.exception.ts, server/src/exceptions/reason-required.exception.ts, server/src/user/user.controller.ts, server/src/video/dto/video-rating-response.dto.ts, server/src/video/dto/video-rating.dto.ts, server/src/video/schemas/video.schema.ts, server/src/video/video.controller.ts, server/src/video/video.module.ts, server/src/video/video.service.ts
resolved: #97 
- 별점 등록 및 수정 API 작성
- 트랜잭션 사용으로 원자성 보장
- inc, push 연산 사용으로 고립성 보장
- 조회수 증가 서비스 로직 작성
- 각 API Swagger 명세에 summary 추가
=> 비디오 별점 등록/수정

client/data/build.gradle.kts, client/data/src/main/java/com/everyone/data/base/BaseResponse.kt, client/data/src/main/java/com/everyone/data/mapper/Mapper.kt, client/data/src/main/java/com/everyone/data/remote/NetworkHandler.kt, client/data/src/main/java/com/everyone/data/remote/model/ApiResponse.kt, client/data/src/main/java/com/everyone/data/remote/model/UrlParams.kt, client/data/src/main/java/com/everyone/data/remote/model/UrlParamsBuilder.kt, client/domain/src/main/java/com/everyone/domain/model/base/BaseModel.kt, client/presentation/src/main/java/com/everyone/movemove_android/di/NetworkHandlerModule.kt
resolved: #110
- `BaseResponse`, `BaseModel` 구현
- 도메인 레이어에 선언된 데이터 스펙에 따라 데이터 레이어의 데이터를 변환할 수 있는 `Mapper` 구현
- `NetworkHandler` 의존성 주입 구현
=> 네트워크 통신 구조 적용

client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/watching_video/WatchingVideoScreen.kt
resolved: #55 
- 비디오 페이지가 완전히 바뀌었을 때 ExoPlayer 실행
- 백그라운드 이동 시 ExoPlayer 정지
=> 비디오 스트리밍 후 백그라운드로 이동 시 ExoPlayer 정지

client/data/src/main/java/com/everyone/data/remote/NetworkHandler.kt, client/data/src/main/java/com/everyone/data/remote/model/UploaderResponse.kt, client/data/src/main/java/com/everyone/data/remote/model/VideoRandomResponse.kt, client/data/src/main/java/com/everyone/data/remote/model/VideoResponse.kt, client/data/src/main/java/com/everyone/data/remote/model/VideosRandomResponse.kt, client/data/src/main/java/com/everyone/data/repository/MainRepositoryImpl.kt, client/domain/src/main/java/com/everyone/domain/model/Uploader.kt, client/domain/src/main/java/com/everyone/domain/model/Video.kt, client/domain/src/main/java/com/everyone/domain/model/VideoRandom.kt, client/domain/src/main/java/com/everyone/domain/model/VideosRandom.kt, client/domain/src/main/java/com/everyone/domain/repository/MainRepository.kt, client/domain/src/main/java/com/everyone/domain/usecase/GetVideoRandomUseCase.kt, client/domain/src/main/java/com/everyone/domain/usecase/PutVideosRatingUseCase.kt, client/presentation/src/main/java/com/everyone/movemove_android/di/RepositoryModule.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/watching_video/WatchingVideoViewModel.kt
resolved: #107
- 랜덤으로 비디오 응답 API 연결
- 비디오 별점 등록/수정 API 연결
- 토큰 값은 임시적으로 헤더에 넣을 수 있게 수정했습니다.
- 랜덤으로 비디오 응답 API는 서버측에서 수정할 가능성이 있어 데이터를 렌더링 하지 않았습니다.
=> 비디오 스트리밍 페이지 API 연결

server/src/ncpAPI/common.ts, server/src/user/dto/rated-video-request.dto.ts, server/src/user/dto/rated-video-response.dto.ts, server/src/user/dto/rater-response.dto.ts, server/src/user/user.controller.ts, server/src/user/user.module.ts, server/src/user/user.service.ts, server/src/video/dto/rated-video-info.dto.ts, server/src/video/video.controller.ts, server/src/video/video.service.ts
resolved: #98
- uuid가 일치하는 User Document에서 내장된 Action Document들 중 updatedAt 기준으로 limit개 가져옴
- 존재하지 않는 user 예외처리
- limit개 가져오기 위해 client가 마지막으로 조회한 비디오의 ratedAt 값을 넘겨줘야 합니다.
- ratedAt은 client와 데이터를 주고 받을 때만 사용되며, dto를 참고해주시면 될 것 같습니다.
=> 특정 유저가 별점을 준 비디오 조회

server/src/action/action.service.ts, server/src/app.controller.ts, server/src/exceptions/enum/exception.enum.ts, server/src/exceptions/reason-required.exception.ts, server/src/user/user.module.ts, server/src/user/user.service.ts, server/src/video/dto/ads-response.dto.ts, server/src/video/dto/video-list-response.dto.ts, server/src/video/video.controller.ts, server/src/video/video.service.ts
resolved: #128 
- 별점 준 비디오 정렬 우선순위 수정
- 비디오 리스트 응답 구조 수정
=> 별점 준 비디오 페이지네이션 버그 수정

client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingScreen.kt
=> Starting 배경화면 영상 사이즈 버전 대응

.github/workflows/BE_CD.yml
relatedTo: #136 
- ssh action 포트 설정
=> BE CD 배포 설정

.github/workflows/BE_CD.yml, server/src/main.ts
relatedTo : #117 
- Docker build 단계 registry 캐시 사용
=> BE CD Docker 빌드 캐시 사용 테스트

client/presentation/src/main/java/com/everyone/movemove_android/ui/image_cropper/ImageCropperViewModel.kt
resolved: #168
- 계산을 위해 필요한 변수들을 지역화하여 가독성 개선
=> ImageCropper 코드 가독성 개선

client/data/build.gradle.kts, client/data/src/main/java/com/everyone/data/local/UserInfoManager.kt, client/gradle/libs.versions.toml, client/presentation/build.gradle.kts, client/presentation/src/main/java/com/everyone/movemove_android/di/CoroutineDispatcherModule.kt, client/presentation/src/main/java/com/everyone/movemove_android/di/CoroutineDispatcherQualifiers.kt, client/presentation/src/main/java/com/everyone/movemove_android/di/RepositoryModule.kt, client/presentation/src/main/java/com/everyone/movemove_android/di/UserInfoManagerModule.kt
resolved: #134
- `AccessToken`, `RefreshToken`, `UserId` 를 관리하는 `UserInfoManager` 구현
=> 토큰 및 UserId 관리 객체 구현

client/data/src/main/java/com/everyone/data/remote/model/ProfileResponse.kt, client/data/src/main/java/com/everyone/data/repository/UserRepositoryImpl.kt, client/domain/src/main/java/com/everyone/domain/model/Profile.kt, client/domain/src/main/java/com/everyone/domain/repository/UserRepository.kt, client/domain/src/main/java/com/everyone/domain/usecase/GetProfileUseCase.kt, client/presentation/src/main/java/com/everyone/movemove_android/di/RepositoryModule.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/my/MyContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/my/MyScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/my/MyViewModel.kt
resolved: [#156]
- 마이 화면에서 프로필 조회 API 연결 하였습니다.
- 이후 uid,토큰 매니저가 나오면 이와 연결하겠습니다.
=> 마이 화면 프로필 조회 API 연동

client/presentation/src/main/java/com/everyone/movemove_android/ui/my/MyContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/my/MyScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/my/MyViewModel.kt, client/presentation/src/main/res/values/strings.xml
resolved: [#182]
- 서버로 부터 받은 이미지와 닉네임 연동 
- 닉네임이 null일때는 effect로 앱을 종료시켰습니다 발생한 가능성은 희박하지만 만약 발생한다면 이를 사용자에게 알려줄 적절한 방법이 있을까요 ?
=> 마이화면 프로필이미지,닉네임 앱에 연동

client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/watching_video/WatchingVideoScreen.kt
resolved: #172 
- 하나의 ExoPlayer에서 여러개의 영상이 동시 실행되는 이슈 해결
=> 하나의 ExoPlayer에서 여러개의 영상이 동시 실행되는 이슈

client/data/src/main/java/com/everyone/data/remote/RemoteConstants.kt, client/data/src/main/java/com/everyone/data/repository/UserRepositoryImpl.kt, client/domain/src/main/java/com/everyone/domain/repository/UserRepository.kt, client/domain/src/main/java/com/everyone/domain/usecase/LoginUseCase.kt, client/presentation/src/main/java/com/everyone/movemove_android/di/UseCaseModule.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/sign_up/SignUpViewModel.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingViewModel.kt
=> 자동 로그인 기능 구현

client/data/src/main/java/com/everyone/data/remote/RemoteConstants.kt, client/data/src/main/java/com/everyone/data/remote/model/AdsResponse.kt, client/data/src/main/java/com/everyone/data/remote/model/AdvertisementsResponse.kt, client/data/src/main/java/com/everyone/data/remote/model/VideoResponse.kt, client/data/src/main/java/com/everyone/data/repository/AdsRepositoryImpl.kt, client/domain/src/main/java/com/everyone/domain/model/Advertisements.kt, client/domain/src/main/java/com/everyone/domain/model/Video.kt, client/domain/src/main/java/com/everyone/domain/repository/AdsRepository.kt, client/domain/src/main/java/com/everyone/domain/usecase/GetAdsUseCase.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeViewModel.kt
resolved: #189 
- 홈 페이지 API 렌더링 진행
=> 홈 페이지 API 렌더링

client/data/src/main/java/com/everyone/data/remote/RemoteConstants.kt, client/data/src/main/java/com/everyone/data/repository/UserRepositoryImpl.kt
resolved: #214 
- `profileImageExtension`, `profileExtension` 을 혼용하도록 수정
=> API 필드명 변경에 따른 수정

client/data/src/main/java/com/everyone/data/remote/model/UploaderResponse.kt, client/domain/src/main/java/com/everyone/domain/model/Uploader.kt, client/presentation/src/main/AndroidManifest.xml, client/presentation/src/main/java/com/everyone/movemove_android/ui/container/ContainerActivity.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/container/ContainerScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeViewModel.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/VideoPagingSource.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoActivity.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoViewModel.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/category/CategoryScreen.kt
resolved: #196 
- 비디오 스트리밍 페이지, Screen에서 Activity로 변경
=> 비디오 스트리밍 페이지, Screen에서 Activity로 변경

client/presentation/src/main/java/com/everyone/movemove_android/ui/Dialogs.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoViewModel.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/VideoTrimmer.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/util/ComposableUtil.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/util/VideoUtil.kt, client/presentation/src/main/res/values/strings.xml
resolved: #201, #155, #149, #159, #161, #162, #160, #150, #151
- 비디오 업로드 관련 예외 처리
- 비디오 편집 관련 예외 처리
=> 비디오 업로드 리팩토링

client/data/src/main/java/com/everyone/data/remote/RemoteConstants.kt, client/data/src/main/java/com/everyone/data/remote/model/VideosRatedItemResponse.kt, client/data/src/main/java/com/everyone/data/repository/UserRepositoryImpl.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/rating_video/RatingVideoActivity.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/rating_video/RatingVideoContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/rating_video/RatingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/rating_video/RatingVideoViewModel.kt
resolved: #210 
- 코드 컨벤션 확인
- 구조 개선
=> 내가 점수를 남긴 영상 모아보기 리팩토링 

client/data/src/main/java/com/everyone/data/repository/VideosRepositoryImpl.kt, client/domain/src/main/java/com/everyone/domain/repository/VideosRepository.kt, client/domain/src/main/java/com/everyone/domain/usecase/GetVideosRandomUseCase.kt, client/domain/src/main/java/com/everyone/domain/usecase/PutVideosRatingUseCase.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoActivity.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoViewModel.kt
resolved: #208 
- 코드 컨벤션 확인
- 구조 개선
- 프로필 클릭시 프로필 페이지로 이동
=> 비디오 스트리밍 페이지 리팩토링

client/presentation/src/main/java/com/everyone/movemove_android/ui/sign_up/SignUpContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/sign_up/SignUpScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/sign_up/SignUpViewModel.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingViewModel.kt, client/presentation/src/main/res/values/strings.xml
resolved: #220, #221 
- 로그인 시 UUID 저장
- 회원 가입 예외 발생 시 다이얼로그 표시
- 회원 가입 프로필 이미지 설정 영역 확대
- @upsk1 추후 리팩토링 기간에 `SignUpScreen.kt` 파일 리팩토링 해주시면 됩니다 :)
=> 로그인 및 가입 예외 처리

client/presentation/src/main/java/com/everyone/movemove_android/ui/my/MyContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/my/MyScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/my/MyViewModel.kt
resolved: [#198]
- 마이화면에서 다른 화면으로 넘어가는 이벤트 구현
- 본인 uuid를 사용하여 API 조회 구현
=> MY화면 API 연결 및 버튼클릭 이벤트 추가

client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoViewModel.kt
resolved: #204 
- 비디오 스트리밍 페이지 예외처리
- 특정 비디오 클릭시 실행 안되는 이슈 해결
=> 비디오 스트리밍 페이지 예외처리

client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeViewModel.kt, client/presentation/src/main/res/values/strings.xml
=> 홈 페이지 예외처리

client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/FrameExtractor.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoViewModel.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingViewModel.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/util/VideoUtil.kt
resolved: #244 
- `MediaCodec` 이용하여 프레임 획득 코드 리팩토링
- 영상 크기 및 회전값에 대한 대응
=> 프레임 획득 리팩토링

client/presentation/src/main/java/com/everyone/movemove_android/ui/CommonComposables.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/profile/ProfileActivity.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/profile/ProfileContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/profile/ProfileScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/profile/ProfileViewModel.kt, client/presentation/src/main/res/values/strings.xml
resolved: #205 
- API 통신 에러시 에러 스크린 생성
- 뒤로가기 버튼 생성
=> 프로필 페이지 예외처리

client/data/src/main/java/com/everyone/data/remote/NetworkHandler.kt, client/data/src/main/java/com/everyone/data/repository/AdsRepositoryImpl.kt, client/data/src/main/java/com/everyone/data/repository/VideosRepositoryImpl.kt, client/domain/src/main/java/com/everyone/domain/repository/VideosRepository.kt, client/domain/src/main/java/com/everyone/domain/usecase/GetVideoWithIdUseCase.kt, client/presentation/src/main/java/com/everyone/movemove_android/di/UseCaseModule.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoViewModel.kt
resolved: #247 
- 업로드 로직에 예외 처리가 필요한 부분 구현
- 업로드 이후의 액션 구현
=> 업로드 관련 추가 예외 처리

client/data/src/main/java/com/everyone/data/remote/RemoteConstants.kt, client/data/src/main/java/com/everyone/data/repository/UserRepositoryImpl.kt, client/domain/src/main/java/com/everyone/domain/repository/UserRepository.kt, client/domain/src/main/java/com/everyone/domain/usecase/GetProfileImageUploadUrlUseCase.kt, client/domain/src/main/java/com/everyone/domain/usecase/LoginUseCase.kt, client/domain/src/main/java/com/everyone/domain/usecase/SignUpUseCase.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/UiConstants.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/sign_up/SignUpActivity.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/sign_up/SignUpViewModel.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingViewModel.kt
resolved: [#246]
- 로그인 회원가입 API 명세 변경 및 실제 동작 확인
=> 로그인, 회원가입 API 명세 변경

client/presentation/src/main/java/com/everyone/movemove_android/ui/CommonComposables.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/container/ContainerScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeViewModel.kt, client/presentation/src/main/res/values/strings.xml
resolved: #254 
- 뉴스쿨, K-POP 리스트뷰 추가
- 비디오 아이템뷰 제목 추가
- 홈에서 뒤로가기 2번시 앱 종료
=> 홈 페이지 UI 리팩토링

client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoViewModel.kt, client/presentation/src/main/res/values/strings.xml
resolved: #259 
- 인코딩 중 영상 재생되지 않도록 수정
- 예외 상황에 다이얼로그 표시하도록 구현
- 영상 업로드 이후 추가 업로드 시 정상 작동하도록 수정
=> 인코딩 중에도 동영상 재생 되는 오류 수정

client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingScreen.kt
resolved: [#261]
- 카카오톡 없이 카카오 로그인 구현
=> 카카오톡 앱 없이 로그인 구현

client/presentation/src/main/AndroidManifest.xml, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoScreen.kt
resolved: #263 
- 점수 남기기에 슬라이더 위 라벨 개선
=> 점수 남기기에 슬라이더 위 라벨 개선

client/presentation/src/main/AndroidManifest.xml
resolved: #265 
- 액티비티 세로모드 고정
=> 액티비티 세로 모드 고정

client/gradle/libs.versions.toml, client/presentation/src/main/java/com/everyone/movemove_android/ui/watching_video/WatchingVideoScreen.kt
resolved: #266 
- 비디오 스트리밍 비디오 크기 대응
- 비디오 버벅임 개선
=> 비디오 스트리밍 비디오 크기 대응

client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/FrameExtractor.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoViewModel.kt, client/presentation/src/main/res/values/strings.xml
resolved: #260 
- 추출이 안되는 경우는 특수한 경우라 판단하고 예외 처리
=> 프레임을 획득할 수 없는 영상에 대한 예외 처리

client/presentation/src/main/java/com/everyone/movemove_android/ui/profile/ProfileScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/rating_video/RatingVideoScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeContract.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeScreen.kt, client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeViewModel.kt
resolved: #272 
- 홈, 프로필 페이지 라이프 사이클을 통한 UI 상태 업데이트
=> 라이프 사이클을 통한 상태 업데이트

server/src/action/action.controller.ts, server/src/video/video.controller.ts
=> API 요청 확인을 위한 로그 출력

client/presentation/src/main/java/com/everyone/movemove_android/ui/sign_up/SignUpScreen.kt, client/presentation/src/main/res/values/strings.xml
resolved: [#282 ]
- 프로필 이미지 미등록시 안내 문구 출력 구현
=>  프로필 이미지 미등록시 안내 문구 출력
